parameters:
  SourceDirectory: ''
  JobName: Test
  TestTimeoutInMinutes: 30
  MaxParallel: 4
  VmImage: ubuntu-16.04
  Matrix:
    Python38:
      Container: teqniqly/azure-pipeline-job-python:3.8.3-alpine

jobs:
  - job: ${{ parameters.JobName }}
    timeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}
    strategy:
      maxParallel: ${{ parameters.MaxParallel }}
      matrix: ${{ parameters.Matrix }}
    continueOnError: false
    pool:
      vmImage: ${{ parameters.VmImage }}  
    container: ${{ parameters.Container }}
    steps:
      - template: ../steps/build-test.yml
        parameters:
          SourceDirectory: ${{ parameters.SourceDirectory }}
