parameters:
  SourceDirectory: ''
  JobName: Test
  TestTimeoutInMinutes: 30
  VmImage: ubuntu-16.04
  TestMatrix:
    Python38:
      Container: teqniqly/azure-pipeline-job-python:3.8.3-ubuntu
    Python37:
      Container: teqniqly/azure-pipeline-job-python:3.7.7-ubuntu
    Python36:
      Container: teqniqly/azure-pipeline-job-python:3.6.10-ubuntu

jobs:
  - job: ${{ parameters.JobName }}
    timeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}
    strategy:
      matrix: ${{ parameters.TestMatrix }}
    continueOnError: false
    pool:
      vmImage: ${{ parameters.VmImage }}  
    container: $[ variables['container'] ]
    steps:
      - template: ../steps/build-test.yml
        parameters:
          SourceDirectory: ${{ parameters.SourceDirectory }}
