resources:
  containers:
  - container: py35
    image: teqniqly/azure-pipeline-job-python:3.5.9-alpine

  - container: py36
    image: teqniqly/azure-pipeline-job-python:3.6.10-alpine

  - container: py37
    image: teqniqly/azure-pipeline-job-python:3.7.7-alpine

  - container: py38
    image: teqniqly/azure-pipeline-job-python:3.8.3-alpine

parameters:
  SourceDirectory: ''
  JobName: Test
  TestTimeoutInMinutes: 30
  MaxParallel: 4
  VmImage: ubuntu-16.04
  Matrix:
    Python38:
      ContainerResource: py38

jobs:
  - job: ${{ parameters.JobName }}
    timeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}
    strategy:
      maxParallel: ${{ parameters.MaxParallel }}
      matrix: ${{ parameters.Matrix }}
    continueOnError: false
    pool:
      vmImage: ${{ parameters.VmImage }}  
    container: ${{ parameters.ContainerResource}}
    steps:
      - template: ../steps/build-test.yml
        parameters:
          SourceDirectory: ${{ parameters.SourceDirectory}}
